app/admin/routes.py
from io import BytesIO
from flask import render_template, redirect, url_for, flash, request, send_file, render_template_string, abort
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from sqlalchemy import or_, and_
from app.auth import models
from app.auth import routes
from app.admin import forms as ad_forms
from app.auth import forms as auth_forms
from app.course import forms as crs_forms
from app.auth import forms as auth_forms
from flask.blueprints import Blueprint
from app import db
from datetime import datetime, time
from collections import namedtuple
from app.utils import get_grade_from_range, check_tuple_in_list


admin_bp = Blueprint('admin',  __name__, template_folder='templates', static_folder='static')


@admin_bp.errorhandler(404)
def page_not_found(e):
    # note that we set the 404 status explicitly
    return render_template('admin/error_404.html'), 404


@admin_bp.route('/admin/dashboard')
@login_required
def admin_dashboard():
    if current_user.role not in ['superadmin', 'admin']:
        flash('Sorry, you have to be an admin', 'warning')
        return redirect(url_for('auth.login'))
    supervisors = models.User.query.filter_by(role='supervisor').order_by(models.User.created_at.desc())
    if not supervisors:
        abort(404)
    last_five_supervisors = supervisors.limit(5)
    new_supervisors = [created for created in supervisors if created.status == '1']
    documented_supervisors = [documented for documented in supervisors if documented.status == '3']
    count_new_supervisors = len(list(new_supervisors))
    count_documented_supervisors = len(list(documented_supervisors))
    students = db.session.query(models.Students)
    courses = db.session.query(models.Course)
    l5_students = students.limit(5)
    l5_courses = courses.limit(5)
    students_in_db = students.count()
    tutors_in_db = supervisors.count()
    courses_created = courses.filter(models.Course.status == 'created').count()
    courses_accepted = courses.filter(models.Course.status == 'accepted').count()
    courses_total = courses_accepted + courses_created

    return render_template('admin/admin_dashboard.html', l5_supervisors=last_five_supervisors, count_new_supervisors=count_new_supervisors,
                           new_supervisors=new_supervisors, documented_supervisors=documented_supervisors, l5_students=l5_students,
                           tutors=tutors_in_db, students=students_in_db, courses_t=courses_created, l5_courses=l5_courses,
                           courses_a=courses_accepted, total=courses_total, title='Show tutors', legend='Admin Dashboard')


@admin_bp.context_processor
def context_processor():
    supervisors = models.User.query.filter_by(role='supervisor').order_by(models.User.created_at.desc())
    new_supervisors = [created for created in supervisors if created.status == '1']
    documented_supervisors = [documented for documented in supervisors if documented.status == '3']
    count_new_supervisors = len(list(new_supervisors))
    count_documented_supervisors = len(list(documented_supervisors))
    return dict(count_documented_supervisors=count_documented_supervisors, documented_supervisors=documented_supervisors, count_new_supervisors=count_new_supervisors, new_supervisors=new_supervisors)


@admin_bp.route('/admin/show_tutors')
@login_required
def show_tutors():
    print(current_user.role)
    if current_user.role not in ['superadmin', 'admin']:
        flash('Sorry, you have to be an admin', 'warning')
        return redirect(url_for('auth.login'))
    q_first = request.args.get('q_first')
    q_last = request.args.get('q_last')
    q_subject = request.args.get('q_subject')
    q_modality = request.args.get('q_modality')
    q_day = request.args.get('q_day')

    if q_first:
        q_first = q_first.title()
        tutors = models.User.query.filter_by(role='supervisor').filter(models.User.first_name.contains(q_first))
    if q_last:
        q_last = q_last.title()
        tutors = models.User.query.filter_by(role='supervisor').filter(models.User.last_name.contains(q_last))
    if q_first and q_last:
        q_first = q_first.title()
        q_last = q_last.title()
        tutors = models.User.query.filter_by(role='supervisor').filter(models.User.last_name.contains(q_first)).filter(models.User.last_name.contains(q_last))
    if q_day:
        tutors = models.User.query.join(models.Tutoring).filter(models.Tutoring.tutor_availabilities.any(day_possible=q_day))
    if q_subject:
        tutors = models.User.query.join(models.Tutoring).filter(models.Tutoring.tutor_subjects.any(subject=q_subject))
    if q_modality:
        tutors = models.User.query.join(models.Tutoring).filter(models.Tutoring.tutor_modalities.any(modality=q_modality))
    if q_subject and q_modality:
        tutors = models.User.query.join(models.Tutoring).filter(models.Tutoring.tutor_modalities.any(modality=q_modality)).filter(models.Tutoring.tutor_subjects.any(subject=q_subject))
    if q_subject and q_day:
        tutors = models.User.query.join(models.Tutoring).filter(models.Tutoring.tutor_availabilities.any(day_possible=q_day)).filter(models.Tutoring.tutor_subjects.any(subject=q_subject))
    if q_modality and q_day:
        tutors = models.User.query.join(models.Tutoring).filter(models.Tutoring.tutor_modalities.any(modality=q_modality)).filter(models.Tutoring.tutor_availabilities.any(day_possible=q_day))
    if q_subject and q_modality and q_day:
        tutors = models.User.query.join(models.Tutoring).filter(models.Tutoring.tutor_modalities.any(modality=q_modality)).filter(models.Tutoring.tutor_subjects.any(subject=q_subject)).filter(models.Tutoring.tutor_availabilities.any(day_possible=q_day))
    if not q_subject and not q_modality and not q_first and not q_last and not q_day:
        tutors = models.User.query.filter_by(role='supervisor').order_by(models.User.created_at)

    return render_template('admin/show_tutors.html', data=tutors, queries=(q_subject, q_modality, q_day, q_first, q_last), title='Show tutors', legend='List of tutors')


@admin_bp.route('/admin/tutors/<int:tutor_id>', methods=['GET', 'POST'])
@login_required
def get_tutor_by_id(tutor_id):
    if current_user.role not in ['superadmin', 'admin']:
        flash('Sorry, you have to be an admin', 'warning')
        return redirect(url_for('auth.login'))
    status_form = ad_forms.ChangeTutorStatus()
    interview_form = ad_forms.PlanInterview()
    form = auth_forms.ProfilePage1Form()
    form2 = auth_forms.ProfilePage2Form()
    form3 = auth_forms.ProfilePage3Form()
    form4 = auth_forms.ValidateInterviewDateForm()
    availability_form = auth_forms.AddAvailabilitiesToTutor()
    modality_form = auth_forms.AddModalityToTutor()
    subjects_form = auth_forms.AddSubjectGradesToTutor()
    selected_tutor = models.User.query.filter_by(id=tutor_id).first_or_404()
    tutor_interviews = selected_tutor.my_interviews

    if status_form.validate_on_submit():
        selected_tutor.status = status_form.status.data
        try:
            db.session.commit()
            flash('Status Updated successfully', 'success')
            return redirect(url_for('admin.get_tutor_by_id', tutor_id=selected_tutor.id))
        except:
            flash('Something wrong happened', 'warning')
            return redirect(url_for('admin.get_tutor_by_id', tutor_id=selected_tutor.id))

    elif request.method == 'POST' and interview_form.validate_on_submit():
        if tutor_interviews:

            if tutor_interviews.interview_date is not None or not interview_form.interviewer:
                tutor_interviews.interview_date = interview_form.interview_date.data.strftime('%Y-%m-%d')
                tutor_interviews.interview_time = interview_form.interview_time.data
                tutor_interviews.interviewer = interview_form.interviewer.data
                tutor_interviews.message = interview_form.message.data
        else:
            update_interviews = models.Interviews(interview_date=interview_form.interview_date.data, interview_time=interview_form.interview_time.data,
                                                  interviewer=interview_form.interviewer.data,
                                                  message=interview_form.message.data, user=selected_tutor)
            selected_tutor.status = '4'
            db.session.add(update_interviews)
            db.session.commit()
        try:
            db.session.commit()
            flash('Interview Planned successfully', 'success')
            return redirect(url_for('admin.get_tutor_by_id', tutor_id=selected_tutor.id))
        except:
            flash('Something wrong happened', 'warning')
            return redirect(url_for('admin.get_tutor_by_id', tutor_id=selected_tutor.id))
    status_form.status.data = selected_tutor.status

    if tutor_interviews and tutor_interviews.interview_time:
        interview_form.interview_date.data = datetime.strptime(tutor_interviews.interview_date, '%Y-%m-%d')
        interview_form.interview_time.data = datetime.strptime(tutor_interviews.interview_time, '%H:%M:%S')
        interview_form.interviewer.data = tutor_interviews.interviewer
        interview_form.message.data = tutor_interviews.message

    if selected_tutor.my_info is not None:
        form.address.data = selected_tutor.my_info.address
        form.city.data = selected_tutor.my_info.city
        form.zipcode.data = selected_tutor.my_info.zipcode
        form.email2.data = selected_tutor.my_info.email2
        form.phone.data = selected_tutor.my_info.phone
        form.birth_date.data = datetime.strptime(selected_tutor.my_info.birth_date,'%Y-%m-%d')
        form.short_text.data = selected_tutor.my_info.short_text

    if selected_tutor.more is not None:
        form3.why.data = selected_tutor.more.why
        form3.experience.data = selected_tutor.more.experience
        form3.when.data = selected_tutor.more.when

app/course/routes.py
from flask import render_template, redirect, url_for, flash, request,  render_template_string
from flask_login import current_user, login_required
from flask import request
from werkzeug.urls import url_parse
from app.auth import models
from app.course import forms as crs_forms
from app.admin import forms as ad_forms
from app.auth import forms as au_forms
from flask.blueprints import Blueprint
from app import db
from datetime import datetime, time


course_bp = Blueprint('course',  __name__, template_folder='templates', static_folder='static')


@course_bp.route('/courses/students/course_list/<int:student_id>', methods=['GET', 'POST'])
@login_required
def course_list(student_id):
    courses = models.Course.query.all()
    courses_for_student = []
    student_sel = ''
    for course in courses:
        for stud in course.student:
            if stud.id == student_id:
                student_sel = f"{stud.first_name} {stud.last_name}"
                courses_for_student.append(course)

    return render_template('courses/student_course_list.html', data=courses_for_student, title='Course  list for student', legend=f'Courses of {student_sel}')


@course_bp.route('/courses/tutors/course_list/<int:tutor_id>', methods=['GET', 'POST'])
@login_required
def tutor_course_list(tutor_id):
    courses = models.Course.query.all()
    courses_for_tutor = []
    tutor_sel = ''
    for course in courses:
        for tut in course.tutor:
            if tut.id == tutor_id:
                tutor_sel = f"{tut.first_name} {tut.last_name}"
                courses_for_tutor.append(course)

    return render_template('courses/tutor_course_list.html', data=courses_for_tutor, title='Course  list for student', legend=f'Courses of {tutor_sel}')


@course_bp.route('/course/update/<int:course_id>', methods=['GET', 'POST'])
@login_required
def course_update(course_id):
    course_form = crs_forms.UpdateCourseForm()
    course_selected = models.Course.query.filter_by(id=course_id).first()
    print(course_selected.student[0].id)
    print(course_selected.tutor[0].id)

    student = course_selected.student[0]
    tutor = course_selected.tutor[0]

    course_form.subject.data = course_selected.subject
    course_form.selected_day.data = course_selected.selected_day
    course_form.start_time.data = course_selected.start_time
    course_form.end_time.data = course_selected.end_time
    course_form.status.data = course_selected.status

    if request.method == 'POST' and course_form.validate_on_submit():

        course_selected.subject = request.form['subject']
        course_selected.selected_day = request.form['selected_day']
        course_selected.start_time = request.form['start_time']
        course_selected.end_time = request.form['end_time']
        course_selected.status = request.form['status']

        try:
            db.session.commit()
            flash('Course Updated Successfully', 'success')
            return redirect(url_for('course.course_update', course_id=course_selected.id))
        except:
            flash('Something wrong happened', 'warning')
            return redirect(url_for('course.course_update', course_id=course_selected.id))

    course_form.subject.data = course_selected.subject
    course_form.selected_day.data = course_selected.selected_day
    course_form.start_time.data = datetime.strptime(str(course_selected.start_time), "%H:%M")
    course_form.end_time.data = datetime.strptime(str(course_selected.end_time), "%H:%M")
    course_form.status.data = course_selected.status

    return render_template('courses/course_update.html', data=course_selected, student=student, tutor=tutor, form=course_form, title='Course Update', legend='Course Update')


@course_bp.route('/course/delete/<int:course_id>', methods=['GET', 'POST'])
@login_required
def course_delete(course_id):
    course_selected = models.Course.query.filter_by(id=course_id).first()
    print(course_selected.student[0].id)
    student_id = int(course_selected.student[0].id)

    db.session.delete(course_selected)

    try:
        db.session.commit()
        flash('Course deleted', 'info')
        #return redirect(url_for('course.course_list', student_id=course_selected.student[0].id))
    except:
        flash('Something wrong happened', 'danger')
        #return redirect(url_for('course.course_list', student_id=course_selected.student[0].id))

    return redirect(url_for('course.course_list', student_id=student_id))

app/templates/courses/all_course_list.html
{% extends 'base.html' %}

{% from "_macros.html" import render_field, render_fields, switch_status %}

{% block content %}
<div class="row mb-4">
  <div class="col-10 me-0"><h3 class="legend-color">{{ legend }}</h3></div>
  {% include 'auth/breadcrumb_user.html' %}
    <a href="{{url_for('admin.admin_dashboard')}}" class="text-decoration-none desc">Back to Dashboard</a>
</div>
<hr>
<table class="table table-sm">
  <thead>
    <tr>
      <th>Course Id</th>
      <th>Student</th>
      <th>Tutor</th>
      <th>Subject</th>
      <th>Day</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
  {% for course in data %}
    <tr>
      <td>{{course.id}}</td>
      {% for student in course.student %}
      <td>{{ student.first_name}} {{student.last_name}}</td>
      {% endfor %}
      {% for tutor in course.tutor %}
      <td>{{ tutor.first_name}} {{tutor.last_name}}</td>
      {% endfor %}
      <td>{{ course.subject}}</td>
      <td>{{ course.selected_day}}</td>
      <td>{{ course.start_time}}</td>
      <td>{{ course.end_time}}</td>
      <td>{{ course.status}}</td>
      <td><a href="{{url_for('course.course_update', course_id=course.id)}}"><i class="bi bi-pencil-square desc"></i></a></td>
      <td><a href="{{url_for('course.course_delete', course_id=course.id)}}"><i class="bi bi-trash desc"></i></a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

app/templates/courses/course_list.html
{% extends 'base.html' %}

{% from "_macros.html" import render_field, render_fields, switch_status %}

{% block content %}
<div class="row mb-4">
  <div class="col-10 me-0"><h3>{{ legend }}</h3></div>
  {% include 'auth/breadcrumb_user.html' %}
    <a href="{{url_for('admin.student_list')}}" class="text-decoration-none desc">Back to Student List</a>
</div>
<hr>
<table class="table">
  <thead>
    <tr>
      <th>Student</th>
      <th>Tutor</th>
      <th>Subject</th>
      <th>Day</th>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
  </thead>
  <tbody>
  {% for course in data %}
    <tr>
      {% for student in course.student %}
      <td>{{ student.first_name}} {{student.last_name}}</td>
      {% endfor  %}
      {% for tutor in course.tutor %}
      <td>{{ tutor.first_name}} {{tutor.last_name}}</td>
      {% endfor %}
      <td>{{ course.subject}}</td>
      <td>{{ course.selected_day}}</td>
      <td>{{ course.start_time}}</td>
      <td>{{ course.end_time}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

app/templates/courses/course_update.html
{% extends 'base.html' %}

{% from "_macros.html" import render_field, render_fields, switch_status %}

{% block content %}
<div class="row mb-4">
  <div class="col-10 me-0"><h3 class="legend-color">{{ legend }}</h3></div>
  {% include 'auth/breadcrumb_user.html' %}
    <a href="{{url_for('admin.student_list')}}" class="text-decoration-none desc">Back to Student List</a>
</div>
<hr>
<div class="container">
    <div class="row mb-4">
        <table class="table-sm">
            <thead>
                <tr>
                    <th>Course Id</th>
                    <th>Student</th>
                    <th>Tutor</th>
                    <th>Subject</th>
                    <th>Day</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Course Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{data.id}}</td>
                    {% for stud in data.student %}
                    <td>{{stud.first_name}} {{stud.last_name}}</td>
                    {% endfor %}
                    {% for tut in data.tutor %}
                    <td>{{tut.first_name}} {{tut.last_name}}</td>
                    {% endfor %}
                    <td>{{data.subject}}</td>
                    <td>{{data.selected_day}}</td>
                    <td>{{data.start_time}}</td>
                    <td>{{data.end_time}}</td>
                    <td>{{data.status}}</td>
                </tr>
            </tbody>
        </table>
    </div>

    <!-- Button trigger modal -->
    <a href="{{url_for('course.course_update', course_id=data.id)}}" class="btn bg-dark-purple" data-bs-toggle="modal" data-bs-target="#exampleModal">Update this Course</a>

</div>

<!-- Modal Create Course -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update this Course</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" novalidate>
            {{ form.hidden_tag() }}
            <div  class="row">
                <div class="col">
                    <div class="form-outline">
                        <p>{{ student.first_name }} {{ student.last_name }}</p>
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        <p>{{ tutor.first_name }} {{ tutor.last_name }}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-outline">
                        {{ render_field(form.selected_day) }}
                    </div>
                </div>
                <div class="col">
                    <div class="form-outline">
                        {{ form.start_time.label(class="form-label desc mb-0") }}<br>
                        {{ form.start_time(size=10, class="form-control") }}
                        {% for error in form.start_time.errors %}
                        <span class="danger">[{{ error }}]</span>
                        {% endfor %}
                    </div>
                </div>

                <div class="col">
                    <div class="form-outline">
                        {{ form.end_time.label(class="form-label desc mb-0") }}<br>
                        {{ form.end_time(size=10, class="form-control") }}
                        {% for error in form.end_time.errors %}
                        <span class="danger">[{{ error }}]</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <div class="form-outline">
                        {{ render_field(form.subject) }}
                    </div>
                </div>

                <div class="col">
                    <div class="form-outline">
                        {{ render_field(form.status) }}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <p> {{ form.submit(class="btn btn-primary btn-block") }}</p>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/courses/create_course.html
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">Open modal for @mdo</button>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@fat">Open modal for @fat</button>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Open modal for @getbootstrap</button>

{% block modal %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/courses/student_course_list.html
{% extends 'base.html' %}

{% from "_macros.html" import render_field, render_fields, switch_status %}

{% block content %}
<div class="row mb-4">
  <div class="col-10 me-0"><h3 class="legend-color">{{ legend }}</h3></div>
  {% include 'auth/breadcrumb_user.html' %}
    <a href="{{url_for('admin.student_list')}}" class="text-decoration-none desc">Back to Student List</a>
</div>
<hr>
<table class="table table-sm">
  <thead>
    <tr>
      <th>Tutor</th>
      <th>Subject</th>
      <th>Day</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
  {% for course in data %}
    <tr>
      {% for tutor in course.tutor %}
      <td>{{ tutor.first_name}} {{tutor.last_name}}</td>
      {% endfor %}
      <td>{{ course.subject}}</td>
      <td>{{ course.selected_day}}</td>
      <td>{{ course.start_time}}</td>
      <td>{{ course.end_time}}</td>
      <td>{{ course.status}}</td>
      <td><a href="{{url_for('course.course_update', course_id=course.id)}}"><i class="bi bi-pencil-square desc"></i></a></td>
      <td><a href="{{url_for('course.course_delete', course_id=course.id)}}"><i class="bi bi-trash desc"></i></a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

app/templates/courses/tutor_course_list.html
{% extends 'base.html' %}

{% from "_macros.html" import render_field, render_fields, switch_status %}

{% block content %}
<div class="row mb-4">
  <div class="col-10 me-0"><h3 class="legend-color">{{ legend }}</h3></div>
  {% include 'auth/breadcrumb_user.html' %}
    <a href="{{url_for('admin.student_list')}}" class="text-decoration-none desc">Back to Students List</a>
</div>
<hr>
<table class="table table-sm">
  <thead>
    <tr>
      <th>Student</th>
      <th>Subject</th>
      <th>Day</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
  {% for course in data %}
    <tr>
      {% for student in course.student %}
      <td>{{ student.first_name}} {{student.last_name}}</td>
      {% endfor  %}
      <td>{{ course.subject}}</td>
      <td>{{ course.selected_day}}</td>
      <td>{{ course.start_time}}</td>
      <td>{{ course.end_time}}</td>
      <td>{{ course.status}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}